#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
[ProjectConfig]
# Only path variables can and must contain 'DIR', 'PATH' or 'ROOT' in their name as
# these tokens are used to identify path variables from other variable types.
PROJECT_ROOT = "."
PROJECT_NAME = "Mbed Targets"
PROJECT_UUID = "e40a9731-efca-4a89-8a6f-42e53d46622a"
PACKAGE_NAME = "mbed-targets"
NEWS_DIR = "news/"
SOURCE_DIR = "mbed_targets"
RELEASE_BRANCH_PATTERN = "^release.*$"
MODULE_TO_DOCUMENT = "mbed_targets"
DOCUMENTATION_DEFAULT_OUTPUT_PATH = "local_docs"
DOCUMENTATION_PRODUCTION_OUTPUT_PATH = "docs"
VERSION_FILE_PATH = "mbed_targets/_version.py"
CHANGELOG_FILE_PATH = "CHANGELOG.md"
AWS_BUCKET = 'mbed-target'

[AutoVersionConfig]
CONFIG_NAME = "DEFAULT"
PRERELEASE_TOKEN = "beta"
BUILD_TOKEN = "dev"
TAG_TEMPLATE = "release/{version}"
targets = [ "mbed_targets/_version.py",]

[AutoVersionConfig.key_aliases]
__version__ = "VERSION_KEY"
MAJOR = "major"
MINOR = "minor"
PATCH = "patch"
COMMIT = "COMMIT"

[AutoVersionConfig.trigger_patterns]
major = "news/*.major"
minor = "news/*.feature"
patch = "news/*.bugfix"

[tool.towncrier]
directory = "news"
filename = "CHANGELOG.md"
package = "mbed_targets"
title_format = "{version} ({project_date})"
start_string = """
[//]: # (begin_release_notes)
"""

[[tool.towncrier.type]]
directory = "major"
name = "Major changes"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bugfixes"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Improved Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "Deprecations and Removals"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Misc"
showcontent = false

[tool.black]
line-length = 120

[spdx]
CreatorWebsite = "spdx.org"
PathToSpdx = "spdx/spdxdocs"
UUID = "29b28b29-c6c7-4744-9bc5-e7184ac8e5b4"
