"""The version number is based on SemVer.

Breaking changes in SDK will increment the major version number.

references:
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

Validate with:
python -c "from mbed_cloud import __version__; print(__version__)"

This file is autogenerated, do not modify by hand (see auto_version.py)

"""
SDK_MAJOR = '0'
SDK_MINOR = '1'
SDK_PATCH = '0'
_locked = False
__version__ = '0.1.0'
