#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.0.1"
COMMIT = "b4a0be4c6a2594874091e9ca6058e2151c929d47"
MAJOR = 1
MINOR = 0
PATCH = 1
