#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.1.1"
COMMIT = "836436986f53aae507a3bb160a15c0f3a88463f6"
MAJOR = 1
MINOR = 1
PATCH = 1
